services:
  redis:
    image: redis:alpine3.19
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  cast:
    image: cast:latest
    build: .
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NITRO_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - redis

volumes:
  redis-data:
    driver: local
