version: '3.8'

services:
  client:
    build:
      context: ..
      dockerfile: ./docker/client.Dockerfile
    ports:
      - "3000:3000"
    # environment:
    #   - NEXT_PUBLIC_BACK_END_API_URL=http://localhost:3100
    #   - NEXT_PUBLIC_FRONT_END_URL=http://casyu.me
    depends_on:
      - server

  server:
    build:
      context: ..
      dockerfile: ./docker/server.Dockerfile
    ports:
      - "3100:3100"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - PORT=3100
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: