version: '3.8'
name: cast

services:
  client:
    build:
      context: ..
      dockerfile: ./docker/client.Dockerfile
      args:
        NEXT_PUBLIC_BACK_END_API_URL: http://localhost:8080
        NEXT_PUBLIC_FRONT_END_URL: http://casyu.me
    ports:
      - "80:80"
    environment:
      PORT: 80
    depends_on:
      - server
    networks:
      - public

  server:
    build:
      context: ..
      dockerfile: ./docker/server.Dockerfile
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongodb:27017
      PORT: 8080
    depends_on:
      - mongodb
    networks:
      - public
      - internal

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - internal

networks:
  public:
  internal:
    internal: true

volumes:
  mongodb_data:
  mongodb_config: